version: '3.8'
services:
  app:
    build: .
    image: assessment
    container_name: project_assessment
    ports:
      - "8000:80"
    depends_on:
      - mongodb
    environment:
      - OPENAI_API_KEY=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
  mongodb:
    image: "mongo"
    container_name: mongodb
    ports:
      - "27017:27017"
